server:
  port: ${EVENT_PORT:8801}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8000/eureka}

spring:
  datasource:
    url: jdbc:mysql://${EVENT_DB_URL:localhost:3306}/${EVENT_DB_NAME:eventsDb}?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: ${EVENT_DB_USER:root}
    password: ${EVENT_DB_PASSWORD:1}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  error:
    include-message: always

jpa:
  defer-datasource-initialization: true

sql:
  init:
    mode: always
